#################################################################
## Climate
#################################################################

      #################################################################
      ## Turn off Nest if patio door is open for more then 10min
      #################################################################

- alias: climate nest off if patio door open for 10min
  trigger:
    - platform: time_pattern
      minutes: '/10'
  condition:
    - condition: state
      entity_id: sensor.patio_door
      state: 'Open'
    - condition: state
      entity_id: input_boolean.wfh_mode
      state: 'on'
  action:
    - service: climate.set_away_mode
      data:
        away_mode: 'True'
        entity_id: climate.downstairs

      #################################################################
      ## Turn on Nest if patio door is closed
      #################################################################

- alias: climate downstairs nest on if patio door closed
  trigger:
    - platform: state
      entity_id: sensor.patio_door
      to: 'Closed'
  action:
    - service: climate.set_away_mode
      data:
        away_mode: 'False'
        entity_id: climate.downstairs

      #################################################################
      ## Turn on office fan if office is occupied
      #################################################################

- alias: climate office fan on when occupied
  trigger:
    - platform: state
      entity_id: input_boolean.office_occupancy
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.wemo_insight

      #################################################################
      ## Turn Off office fan if not occupied
      #################################################################

- alias: climate office fan off when not occupied
  trigger:
    - platform: state
      entity_id: input_boolean.office_occupancy
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.wfh_mode
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.wemo_insight
