#################################################################
## Visual Notification Automations
#################################################################

        ##########################################################
        ## LGTV Ring Notification
        ##########################################################

- alias: notification visual front door motion
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      to: 'on'
  condition:
    condition: template
    value_template: '{{ states.remote.media_center.state != "off" }}'
  action:
    - service: notify.livingroom_tv
      data:
        message: "Motion detected: Front Door"

- alias: notification visual front door ring
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_ding
      to: 'on'
  condition:
    condition: template
    value_template: '{{ states.remote.media_center.state != "off" }}'
  action:
    - service: notify.livingroom_tv
      data:
        message: "Doorbell pressed: Front Door"
