#################################################################
## System Automations
#################################################################

        ##########################################################
        ## Run Cox Usage Script Hourly
        ##########################################################

- alias: system query cox data usage
  trigger:
    platform: time_pattern
    minutes: '/60'
    seconds: 00
  action:
    service: shell_command.query_cox_data_usage

        ##########################################################
        ## Clean TTS Cache once a week
        ##########################################################

- alias: system clear tts cache
  trigger:
    platform: time_pattern
    hours: '/24'
  condition:
    - condition: time
      weekday:
        - mon
  action:
    service: tts.clear_cache

        ##########################################################
        ## New device connected
        ##########################################################

- alias: system new device connected
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    - service: notify.pushbullet
      data_template:
        message: >
          New device:
          {{trigger.event.data.host_name}}
          ({{trigger.event.data.entity_id}})
          Mac: {{trigger.event.data.mac}}
        title: Home Assistant
